# Site settings
title: Make Your Own Choropleth (alpha)
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thfield.github.io/haiti" # the base hostname & protocol for your site
twitter_username: thfield
github_username:  thfield

# Build settings
markdown: kramdown
